title = "BitXHub configuration file"

solo = false

[port]
  grpc = 60012
  gateway = 9092
  pprof = 53122

[pprof]
  enable = true

[gateway]
    allowed_origins = ["*"]

[log]
  level = "info"
  dir = "logs"
  filename = "bitxhub.log"
  report_caller = false
  [log.module]
    p2p = "info"
    consensus = "info"
    executor = "info"
    router = "info"
    api = "info"
    coreapi = "info"

[cert]
  verify = true

[order]
  plugin = "plugins/raft.so"