site_name: Bitxhub Document
repo_url: https://github.com/meshplus/bitxhub
repo_name: meshplus/bitxhub
extra_css:
  - stylesheets/extra.css
theme:
  logo: /assets/logo.png
  name: material
  palette:
    scheme: blue
    accent: blue
