name: Release

on:
  create:
    tags:
      - v*

jobs:
  release:
    name: Build Release on Linux and Macos
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Check out code
        uses: actions/checkout@v2

      # Executed in the next step
      #- name: Build Binary
      #  run: make release-binary

      - name: Build and Release Binary
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}